version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_ps
      POSTGRES_DB: db_name
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data

  flyway_postgres:
    image: flyway/flyway
    command: -schemas="dorameter" -user="user" -password="user_ps" -url="jdbc:postgresql://postgres:5432/db_name" -connectRetries=10 migrate
    volumes:
      - ./server/repositories/migrations:/flyway/sql
    depends_on:
      - postgres

volumes:
  postgresdata:
