version: "3.8"

services:
  postgres:
    image: postgres:9.6.23-alpine3.14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_ps
      POSTGRES_DB: db_name
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata:
