name: pr-verify

on: pull_request

jobs:
  build:
    name: pr-verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        id: checkout
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js 14.16.1
        uses: actions/setup-node@v1
        id: setup-node
        with:
          node-version: 14.16.1

      - name: Installs dependencies
        run: yarn --no-progress

      - name: Runs linter and tests
        run: yarn dev & yarn verify
