name: pr-verify

on: pull_request

jobs:
  build:
    name: pr-verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        id: checkout
      - name: Use Node.js 12.18.3
        uses: actions/setup-node@v1
        id: setup-node
        with:
          node-version: 12.18.3
      - run: yarn --no-progress
      - run: yarn veirfy
