name: pr-verify

on: pull_request

jobs:
  build:
    name: pr-verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        id: checkout
        with:
          ref: ${{ github.head_ref }}
      - name: Build the docker-compose stack
        run: docker-compose up -d --build
      - name: Use Node.js 12.18.3
        uses: actions/setup-node@v1
        id: setup-node
        with:
          node-version: 12.18.3
      - name: Installs dependencies
        run: yarn --no-progress
      - name: Migrate database
        run: yarn migrate -e localhost
      - name: Runs linter and tests
        run: yarn verify
      - name: Test coverage auto-commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Test coverage auto-commit
